name: Waypoint CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged --entrypoint "" 

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Checkout waypoint-plugin-nixpacks
      uses: actions/checkout@v3
      with:
        repository: thiskevinwang/waypoint-plugin-nixpacks

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Run Waypoint
      uses: docker://registry.gitlab.com/gitlab-org/waypoint-images:latest
      with:
        entrypoint: /bin/sh
        args: |
          -c "export WAYPOINT_SERVER_ADDR=${{ secrets.WAYPOINT_SERVER_ADDR }}
             export WAYPOINT_SERVER_TOKEN=${{ secrets.WAYPOINT_SERVER_TOKEN }}
             export WAYPOINT_SERVER_TLS='1'
             export WAYPOINT_SERVER_TLS_SKIP_VERIFY='1'
             waypoint init
             waypoint up"
      env:
        DOCKER_BUILDKIT: 1
