name: "Runs a Waypoint deployment on merge"
on:
  # once a day, at the end of the day
  #schedule:
  #  - cron: "0 0 * * *"
  push:
    branches:
      - main
      - prod
      - test
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          # Install the latest Waypoint CLI
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install waypoint

          # Create a CLI context to hook up to a Waypoint server
          waypoint context create \
            -server-addr=${{ secrets.WAYPOINT_SERVER_ADDR }} \
            -server-auth-token=${{ secrets.WAYPOINT_SERVER_ADDR }} \
            -server-require-auth=true -server-tls-skip-verify \
            -server-platform="nomad" \
            -set-default \
            waypoint-gh-runner

      - run: |
          # Run the pipeline!
          waypoint version 
          waypoint context list -vv
          waypoint init -v
          waypoint up 