# This workflow uses a GitHub action runner & Waypoint CLI,
# which effectively functions as a Waypoint runner.

name: Waypoint
run-name: Waypoint

on:
  # Using workflow dispatch for ease of manual testing.
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      WAYPOINT_SERVER_TOKEN: ${{ secrets.WAYPOINT_SERVER_TOKEN }}
      WAYPOINT_SERVER_ADDR: ${{ secrets.WAYPOINT_SERVER_ADDR }}
      WAYPOINT_SERVER_TLS: 1
      WAYPOINT_SERVER_TLS_SKIP_VERIFY: 1
    
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/action-setup-waypoint
        with:
          version: '0.1.0'
      - run: waypoint init
      - run: waypoint up